### ISSUE TITLE
Mistake in pin numbering for HAT connector on datasheet

### ISSUE THREAD

**Issue by martenjacobs** [balena-io/balena-fin#35]
In the datasheet for the Fin v1.1 there's a pinout for the HAT connector. On pin 13, the name is `GPIO27`, but the description is `Compute Module GPIO_13`. According to [pinout.xyz](https://pinout.xyz), the correct value is 27.

**Comment by ntzovanis** [comment]
@martenjacobs what you mention seems to be correct. @curcuz @Bucknalla do you confirm? 

Thank you for the heads up!

**Comment by Bucknalla** [comment]
@ntzovanis I can confirm, this looks like a mistake on the datasheet. Thanks for catching this @martenjacobs!
