### ISSUE TITLE
pin1 on USB pin header not actually indicated by a triangle

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-fin#38]
The Datasheet says that pin1 can be identified by a triangle, but there’s no triangle on the Fin. Nico explained that pin1 is closest to the coprocessor, and the other pins follow the standard USB pinout.

**Comment by Bucknalla** [comment]
Hey @shaunmulligan I believe Nico has handled this in PR #37

**Comment by shaunmulligan** [comment]
ah cool @Bucknalla didn't know that. I'll close this then. thanks!
