### ISSUE TITLE
Part number

### ISSUE THREAD

**Issue by TechOverflow** [balena-io/balena-fin#44]
Sorry for not posting a real issue. I am just wondering if you guys could share the part number of those nylon/plastic mPCIE clip-on standoffs. I have never seen them before.

Thanks!

**Comment by ntzovanis** [comment]
Hey @TechOverflow [this](https://www.digikey.com/product-detail/en/essentra-components/DLCBST-1-01/RPC1496-ND/391342) is the part number for the mPCIE standoffs.

**Comment by TechOverflow** [comment]
Thanks!
